[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirects (đảm bảo index.html không bị redirect)
[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/index.html/*"
  to = "/index.html/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Đặc biệt cho index.html - cache ngắn hơn để test
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=60"
